routes/web.php
<?php

use App\Http\Controllers\SmsController;
use App\Http\Controllers\UsahaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('usaha', UsahaController::class);
    Route::resource('sms', SmsController::class);
    Route::post('/sms/write/', [SmsController::class, 'writeSms'])->name('sms.write');;
});

require __DIR__ . '/auth.php';

app/Models/Usaha.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Usaha extends Model
{
    use HasFactory;

    protected $table = 'usaha';

    protected $fillable = [
        'user_id',
        'nama_usaha',
        'nib',
        'jenis_usaha',
        'perizinan_id',
        'jenis_badan_usaha_id',
        'alamat_usaha',
        'aset',
        'rata_omset_perbulan',
        'karyawan_lk',
        'karyawan_pr',
    ];

    protected $hidden = [
        'created_at',
        'updated_at'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function perizinan()
    {
        return $this->hasMany(Perizinan::class, 'usaha_id');
    }

    public function jenisBadanUsaha()
    {
        return $this->belongsTo(JenisBadanUsaha::class, 'jenis_badan_usaha_id');
    }

    public function gambar()
    {
        return $this->hasMany(Foto::class, 'usaha_id');
    }
}

app/Http/Controllers/UsahaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreRequestUsaha;
use App\Http\Requests\UpdateRequestUsaha;
use App\Models\Foto;
use App\Models\JenisBadanUsaha;
use App\Models\Perizinan;
use App\Models\Usaha;
use App\Models\User;

class UsahaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $daftarUsaha = Usaha::with('user')->get();
        return view('usaha.listumkm')->with(['tittle' => 'LIST UMKM', 'daftarUsaha' => $daftarUsaha]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $daftarJenisBadanUsaha = JenisBadanUsaha::all();
        return view('usaha.create', ['tittle' => 'CREATE', 'daftarJenisBadanUsaha' => $daftarJenisBadanUsaha]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequestUsaha $request)
    {

        //input user
        $user = new User;
        $user->nik            = $request->nik;
        $user->nama           = $request->nama;
        $user->jenis_kelamin  = $request->jenis_kelamin;
        $user->no_hp          = $request->no_hp;
        $user->alamat         = $request->alamat;
        $user->password       = bcrypt(strtolower(preg_replace("/[^a-zA-Z]/", "", $request->nama)) . "123");
        $user->save();

        //menetapkan role pengusaha
        $userById = User::find($user->id);
        $userById->assignRole('pengusaha');

        //input data usaha
        $usaha = new Usaha(
            [
                'nama_usaha'            => $request->nama_usaha,
                'nib'                   => $request->nib,
                'jenis_usaha'           => $request->jenis_usaha,
                'jenis_badan_usaha_id'  => $request->jenis_badan_usaha,
                'alamat_usaha'          => $request->alamat_usaha,
                'aset'                  => $request->aset,
                'rata_omset_perbulan'   => $request->rata_omset_perbulan,
                'karyawan_lk'           => $request->karyawan_lk,
                'karyawan_pr'           => $request->karyawan_pr,
            ]
        );
        $saveUsaha =  $userById->usaha()->save($usaha);

        //input data izin
        foreach ($request->perizinan as $izin) {
            $perizinan = new Perizinan(
                [
                    'tanggal'       => $izin['tanggal'],
                    'iumk_nomor'    => $izin['iumk'],
                    'kbli_id'       => $izin['kbli_id']
                ]
            );
            $usahaById = Usaha::find($saveUsaha->id);
            $usahaById->perizinan()->save($perizinan);
        }

        // input gambar logo
        $imgLogoName = 'logo_' . $request->file('logo')->hashName();
        $request->file('logo')->storeAs('public/uploads/img', $imgLogoName);
        $gambarLogo = new Foto(
            [
                'foto'          => 'storage/uploads/img/' . $imgLogoName,
                'jenis_foto'    => "logo",
                'nama_foto'     => "Logo " . $saveUsaha->nama_usaha
            ]
        );
        $usahaById = Usaha::find($saveUsaha->id);
        $usahaById->gambar()->save($gambarLogo);

        //input gambar produk
        foreach ($request->file('produk') as $key => $imgProduk) {
            $imgProdukName      = 'produk_' . $imgProduk->hashName();
            $imgProduk->storeAs('public/uploads/img', $imgProdukName);
            $gambarProduk  = new Foto(
                [
                    'foto'          => 'storage/uploads/img/' . $imgProdukName,
                    'jenis_foto'    => "produk",
                    'nama_foto'     => "Produk " . $key + 1
                ]
            );
            $usahaById = Usaha::find($saveUsaha->id);
            $usahaById->gambar()->save($gambarProduk);
        }

        //input gambar lokasi
        foreach ($request->file('lokasi') as $key => $imgLokasi) {
            $imgLokasiName      = 'lokasi_' . $imgLokasi->hashName();
            $imgLokasi->storeAs('public/uploads/img', $imgLokasiName);
            $gambarLokasi  = new Foto(
                [
                    'foto'          => 'storage/uploads/img/' . $imgLokasiName,
                    'jenis_foto'    => "lokasi",
                    'nama_foto'     => "Lokasi " . $key + 1
                ]
            );
            $usahaById = Usaha::find($saveUsaha->id);
            $usahaById->gambar()->save($gambarLokasi);
        }

        return redirect()->route('usaha.create')->with(['message' => 'Usaha Baru Berhasil Diinput']);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //Mendapatkan daftar jenis badan usaha
        $daftarJenisBadanUsaha = JenisBadanUsaha::all();

        //Mendapatkan relasi usaha   
        $relasiUsahaById = Usaha::where('id', $id)->with('user', 'jenisBadanUsaha', 'gambar', 'perizinan', 'perizinan.kbli')->get();

        //Jika gambar tidak ada maka tampilkan gambar alternatif
        if ($relasiUsahaById[0]->gambar == []) {
            $logo = 'img/picture.png';
            $lokasi[] = '';
            $produk[] = '';
        }

        foreach ($relasiUsahaById[0]->gambar as $gambar) {
            //Jika logo ada, masukan ke variabel logo
            if ($gambar->jenis_foto === 'logo') {
                $logo = $gambar->foto;
            }

            //Jika jenis foto tidak ada logo, maka buat logo alternatif
            if ($gambar->jenis_foto != 'logo') {
                $logoAlt = 'img/picture.png';
            }

            //Jika gambar produk ada maka masukan ke array produk, jika tidak maka beri string kosong
            if ($gambar->jenis_foto === 'produk') {
                $produk[] = $gambar;
            } else {
                $produk[] = '';
            }

            //Jika gambar lokasi ada maka masukan ke array produk, jika tidak maka beri string kosong
            if ($gambar->jenis_foto === 'lokasi') {
                $lokasi[] = $gambar;
            } else {
                $lokasi[] = '';
            }
        }

        return view('usaha.edit', ['tittle' => 'EDIT', 'daftarJenisBadanUsaha' => $daftarJenisBadanUsaha, 'relasiUsahaById' => $relasiUsahaById, "logo" => (isset($logo) ? $logo : $logoAlt), "lokasi" => $lokasi, "produk" => $produk]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequestUsaha $request, $id)
    {
        //Mencari Usaha Sesuai Id Usaha
        $usahaById = Usaha::find($id);
        $userById = User::find($usahaById->user_id);

        // Update User
        $password = bcrypt(strtolower(preg_replace("/[^a-zA-Z]/", "", $request->nama)) . "123");
        $arrayUser = array(

            'nik'           => $request->nik,
            'nama'          => $request->nama,
            'jenis_kelamin' => $request->jenis_kelamin,
            'no_hp'         => $request->no_hp,
            'alamat'        => $request->alamat,
            'password'      => $password

        );
        $userById->update($arrayUser);

        //Update data usaha
        $arrayUsaha = array(
            'nama_usaha'            => $request->nama_usaha,
            'nib'                   => $request->nib,
            'jenis_usaha'           => $request->jenis_usaha,
            'jenis_badan_usaha_id'  => $request->jenis_badan_usaha,
            'alamat_usaha'          => $request->alamat_usaha,
            'aset'                  => $request->aset,
            'rata_omset_perbulan'   => $request->rata_omset_perbulan,
            'karyawan_lk'           => $request->karyawan_lk,
            'karyawan_pr'           => $request->karyawan_pr,
        );
        $userById->usaha()->update($arrayUsaha);

        //update perizinan
        if ($request->has('perizinan')) {
            //Hapus Perizinan
            $perizinanByUsahaId = Perizinan::where('usaha_id', $id)->get();
            foreach ($perizinanByUsahaId as $perizinanByUsahaId) {
                $perizinanByUsahaId->delete();
            }
            //Update data izin
            foreach ($request->perizinan as $izin) {
                $izin = new Perizinan(
                    [
                        'tanggal'       => $izin['tanggal'],
                        'iumk_nomor'    => $izin['iumk'],
                        'kbli_id'       => $izin['kbli_id']
                    ]
                );
                $usahaById->perizinan()->save($izin);
            }
        }

        //Update LOGO
        if ($request->has('logo')) {
            //Hapus Gambar
            $gambarByUsahaId = Foto::where(['usaha_id' => $id, 'jenis_foto' => 'logo'])->get();

            if ($gambarByUsahaId->all() != null) {
                $imagePath = public_path() . '/' . $gambarByUsahaId[0]->foto;
                unlink($imagePath);
                $gambarByUsahaId[0]->delete();
            }


            // Update gambar logo
            $imgLogoName = 'logo_' . $request->file('logo')->hashName();
            $request->file('logo')->storeAs('public/uploads/img', $imgLogoName);
            $gambarLogo = new Foto(
                [
                    'foto'          => 'storage/uploads/img/' . $imgLogoName,
                    'jenis_foto'    => "logo",
                    'nama_foto'     => "Logo " . $usahaById->nama_usaha
                ]
            );
            $usahaById->gambar()->save($gambarLogo);
        }

        //hapus gambar produk
        if ($request->has('imgproduk_id')) {

resources/views/usaha/create.blade.php
@extends('layouts.main')

@section('container')

    @if (session('message'))
        <div style="width: 70%" class="alert alert-success">
            {{ session('message') }}
        </div>
    @endif
    @if ($errors->any())
        <div style="width:70%" class="alert alert-danger">
            <p><strong>Opps Ada Yang Harus Diperbaiki</strong></p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <h2 class="fw-bold mb-5">
        Pendaftaran UMKM Kota Singkawang
    </h2>

    <h3 class="mb-4">
        A. Data Pemilik Usaha
    </h3>

    <form action="{{ route('usaha.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        {{-- NIK --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Nomor Induk Kependudukan (NIK)</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <input type="number" class="form-control p-2" aria-describedby="emailHelp" name="nik" required>
                </div>
            </div>
        </div>

        {{-- Nama Pemilik Usaha --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Nama Pemilik Usaha (sesuai KTP)</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <input type="text" class="form-control p-2" name="nama" required>
                </div>
            </div>
        </div>

        {{-- Jenis Kelamin --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Jenis Kelamin</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-4 d-flex">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="jenis_kelamin" id="flexRadioDefault1"
                            value="Laki-Laki">
                        <label class="form-check-label" for="flexRadioDefault1">
                            Laki-Laki
                        </label>
                    </div>
                    &emsp;
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="jenis_kelamin" id="flexRadioDefault2"
                            value="Perempuan" checked>
                        <label class="form-check-label" for="flexRadioDefault2">
                            Perempuan
                        </label>
                    </div>
                </div>
            </div>
        </div>

        {{-- Alamat --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Alamat Tempat Tinggal</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <textarea class="form-control" name="alamat" id="floatingTextarea2" style="height: 150px"
                        required></textarea>
                </div>
            </div>
        </div>

        {{-- No Hp --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">No. Handphone</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <input type="number" class="form-control p-2" name="no_hp" required>
                </div>
            </div>
        </div>


        <h3 class="mb-4">
            B. Data Usaha
        </h3>

        {{-- Nama Usaha --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Nama Usaha</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <input type="text" class="form-control p-2" name="nama_usaha" required>
                </div>
            </div>
        </div>

        {{-- NIB --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">NIB</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <input type="number" class="form-control p-2" name="nib" required>
                </div>
            </div>
        </div>

        {{-- Produk / Jenis Usaha --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Produk / Jenis Usaha</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <input type="text" class="form-control p-2" name="jenis_usaha" required>
                </div>
            </div>
        </div>

        {{-- Perizinan --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Perizinan yang dimilik & no/tgl</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">

                    <div class="izin-card">
                        <input type="hidden" id="number" value="0">
                        <div class="card p-2 mb-4">
                            <input type="number" class="form-control p-2 mb-3" name="perizinan[0][kbli_id]"
                                placeholder="KBLI" required>
                            <div class="d-flex">
                                <input type="date" class="form-control p-2 me-3" name="perizinan[0][tanggal]" required>
                                <input type="text" class="form-control p-2" name="perizinan[0][iumk]" placeholder="IUMK No."
                                    required>
                            </div>

                        </div>

                    </div>

                    <div>
                        <button type="button" class="btn btn-secondary" style="float: right" onClick="addIzinCard()">Tambah
                            Perizinan</button>
                    </div>

                </div>
            </div>
        </div>

        {{-- Jenis Badan Usaha --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Jenis Badan Usaha</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <select class="form-select" aria-label="Default select example" name="jenis_badan_usaha">
                        @foreach ($daftarJenisBadanUsaha as $jenisBadanUsaha)
                            <option value="{{ $jenisBadanUsaha->id }}">{{ $jenisBadanUsaha->nama }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

        {{-- Alamat Tempat Usaha --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Alamat Tempat Usaha</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <textarea class="form-control" name="alamat_usaha" id="floatingTextarea2" style="height: 150px"
                        required></textarea>
                </div>
            </div>
        </div>

        {{-- Asset --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Asset</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <input type="text" class="form-control p-2" name="aset" required>
                </div>
            </div>
        </div>


        {{-- Rata Omset Perbulan --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Omset Rata - rata per Bulan</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3">
                    <input type="number" class="form-control p-2" name="rata_omset_perbulan" required>
                </div>
            </div>
        </div>

        {{-- Rata Omset Perbulan --}}
        <div class="row align-items-start" style="width:70%">
            <div class="p-2 mb-5 mt-3" style="width:35%;">
                <label style="font-size: 17px">Jumlah Karyawan</label>
            </div>
            <div class="col-1 p-2 mb-5 mt-3" style="width: auto">
                :
            </div>
            <div class="col">
                <div class="mb-5 mt-3 d-flex">
                    <input type="numeric" class="form-control p-2 me-3" placeholder="Laki-Laki" name="karyawan_lk">
                    <input type="numeric" class="form-control p-2" placeholder="Perempuan" name="karyawan_pr">
                </div>
            </div>
        </div>

        {{-- Foto Logo --}}
        <div class="row align-items-start">
            <div class="col-3 p-2 mb-4">
                <label for="formFile" class="text-secondary mb-2">Foto Logo Usaha</label>
                <input class="form-control" type="file" id="formFile" name="logo" required>
            </div>
        </div>

        {{-- Foto Produk --}}
        <div class="row align-items-start">
            <div class="p-2 mb-4" style="width: 60%">
                <label for="formFile" class="text-secondary mb-2">Foto Produk</label>
                <br>
                <input type="hidden" id="number" value="0">
                <button onClick="addImg('.card-produk','produk', 'number')" type="button"
                    class="btn btn-secondary p-2 mb-3">+
                    Produk</button>
                <div class="card-produk d-flex">

                    <div class="card me-3">
                        <div class="card-body mt-4">
                            <input type="file" class="form-control form-control-sm" accept="image/*" name="produk[0]"
                                required>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        {{-- Foto Lokasi --}}
        <div class="row align-items-start">
            <div class="p-2 mb-4" style="width: 60%">
                <label for="formFile" class="text-secondary mb-2">Foto Lokasi</label>
                <br>
                <input type="hidden" id="number" value="0">
                <button onClick="addImg('.card-lokasi','lokasi', 'number')" type="button"
                    class="btn btn-secondary p-2 mb-3">+
                    Lokasi</button>

                <div class="card-lokasi d-flex">

                    <div class="card me-3">
                        <div class="card-body mt-4">
                            <input type="file" class="form-control form-control-sm" accept="image/*" name="lokasi[0]"
                                required>
                        </div>
                    </div>
                </div>


            </div>
        </div>

        <div class="row align-items-start">
            <div class="col- mb-4">
                <button type="submit" class="btn btn-dark" style="width: 70%">SIMPAN UKM BARU</button>
            </div>



        </div>

    </form>




@endsection

resources/views/usaha/listumkm.blade.php
@extends('layouts.main')

@section('container')

    <div style="margin-right:30%">
        @if (session('message'))
            <div style="width: 100%" class="alert alert-success">{{ session('message') }}</div>
        @endif

        @if (session('messageError'))
            <div style="width: 100%" class="alert alert-danger">{{ session('messageError') }}</div>
        @endif

        <h2 class="fw-bold mb-5">
            Data List UKM Singkawang
        </h2>


        <table class="table">
            <thead>
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">Nama Pemilik Usaha</th>
                    <th scope="col">Nama Usaha</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($daftarUsaha as $key => $usaha)
                    <tr>
                        <th scope="row">{{ $key + 1 }}</th>
                        <td>{{ $usaha->user->nama }}</td>
                        <td>{{ $usaha->nama_usaha }}</td>
                        <td>
                            <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                action="{{ route('usaha.destroy', $usaha->id) }}" method="POST">
                                <a href="{{ route('usaha.edit', $usaha->id) }}"
                                    class="btn btn-sm btn-outline-warning">EDIT</a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-outline-danger">HAPUS</button>
                            </form>
                        </td>
                    </tr>

                @endforeach
            </tbody>
        </table>




    </div>








@endsection