routes/web.php
<?php

use App\Http\Controllers\SmsController;
use App\Http\Controllers\UsahaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('usaha', UsahaController::class);
    Route::resource('sms', SmsController::class);
    Route::post('/sms/write/', [SmsController::class, 'writeSms'])->name('sms.write');;
});

require __DIR__ . '/auth.php';

resources/views/partial/sidebar.blade.php
<!-- Sidebar -->
<div class="w3-sidebar w3-light-grey w3-bar-block" style="width:25%">
    <div class="container pt-5" style="margin-top:20%">
        <a href="{{ route('usaha.create') }}"
            class="w3-bar-item btn text-end p-4 {{ $tittle == 'CREATE' ? 'btn-light' : '' }}">Pendaftaran
            UKM</a>
        <a href="{{ route('usaha.index') }}"
            class="w3-bar-item btn text-end p-4 {{ $tittle == 'LIST UMKM' ? 'btn-light' : '' }}">Data List UKM</a>
        <a href="{{ route('sms.index') }}"
            class="w3-bar-item btn text-end p-4 {{ $tittle == 'PESAN MASAL' ? 'btn-light' : '' }}">Kirim Pesan
            Masal</a>
        <form method="POST" action="{{ route('logout') }}">
            @csrf

            <x-responsive-nav-link class="w3-bar-item btn text-end p-4 text-danger" :href="route('logout')" onclick="event.preventDefault();
                                    this.closest('form').submit();">
                {{ __('Log Out') }}
            </x-responsive-nav-link>
        </form>

    </div>

</div>

resources/views/partial/writemessage.blade.php
<div id="card-sms">
    <div class="floating-div">
        <div class="center card-pesan">
            <a href="{{ route('sms.index') }}"><button style="float: right" type="button" class="btn-close"
                    aria-label="Close"></button></a>
            <h3 class=" fs-4 mb-3"><b>Pesan yang ingin dikirim</b></h3>

            <form action="{{ route('sms.store') }}" method="post">
                @csrf
                @foreach (session('userId') as $userId)
                    <input type="hidden" name="user_id[]" value="{{ $userId }}">
                @endforeach
                <textarea style="height: 150px" class="form-control mb-3" placeholder="Leave a comment here"
                    id="floatingTextarea2" style="height: 100px" name="message"></textarea>
                <button type="submit" class="btn btn-dark">Submit Pesan</button>
            </form>
        </div>
    </div>
</div>